apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: techolution-06-sep-2018
  namespace: jenkins
  annotations:
   kubernetes.io/ingress.class: "gce"
spec:
  rules:
  - host: cicd.iface.cloud
    http:
      paths:
      - path: /*
        backend:
          serviceName: jenkins-ui
          servicePort: 8080
  - host: app.iface.cloud
    http:
      paths:
      - path: /*
        backend:
          serviceName: app
          servicePort: 80
