apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app
  namespace: jenkins
spec:
  replicas: 1
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - image: index.docker.io/linux17kartik/app:v0.1
          name: app
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: app
